version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-setup:
    image: mongo
    restart: always
    command: mongorestore --host mongo --port=27017 -u root -p example --authenticationDatabase admin --db=Football_WebApp /database_start
    ports:
      - 8081:8081
    volumes:
      - ./Database_backup/29-01-19/Football_WebApp:/database_start
    links:
      - "mongo"
    

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      DATABASE_URL: mongodb://root:example@mongo:27017
    links:
      - "mongo" 


    
    